version: '3'

services:
  customerbff:
    environment:
      - HOST_IP=10.0.0.215
    image: anudeep96/customer-bff # Replace with the image name for your service1
    network_mode: "host" # Bind host port 8080 to container port 80

  customerservice:
    image: anudeep96/customer-service # Replace with the image name for your service2
    network_mode: "host"

