apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-bff
  namespace: book-store-ns
spec:
  selector:
    matchLabels:
      app: customer-bff
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-bff
    spec:
      containers:
        - name: customer-bff
          image: anudeep96/customer-bff:latest
          ports:
            - containerPort: 82
---
apiVersion: v1
kind: Service
metadata:
  name: customer-bff-service
  namespace: book-store-ns
spec:
  selector:
    app: customer-bff
  ports:
    - name: http
      port: 80
      targetPort: 81
  type: LoadBalancer
