apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-backend
  namespace: book-store-ns
spec:
  selector:
    matchLabels:
      app: customer-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: customer-backend
    spec:
      containers:
        - name: customer-backend
          image: anudeep96/customer-backend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: customer-backend-service
  namespace: book-store-ns
spec:
  selector:
    app: customer-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
