apiVersion: v1
kind: Namespace
metadata:
  name: book-store-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server
  namespace: book-store-ns
spec:
  selector:
    matchLabels:
      app: test-server
  replicas: 1
  template:
    metadata:
      labels:
        app: test-server
    spec:
      containers:
        - name: test-server
          image: anudeep96/test-server:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: test-server-service
  namespace: book-store-ns
spec:
  selector:
    app: test-server
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
